### ISSUE TITLE
Question relative to the contest

### ISSUE THREAD

**Issue by PierreOrhan** [Mathpix/spectra-review-paper-competition#1]
Hello!

Thank you for this initiative and the contest
Some questions relative to the contest:
- Is it possible to review cutting edge **applications** of ML current research in a particular field?  
- Who are the judges of the contest?
- Is anyone allowed to compete?

Thank you!

**Comment by nicodjimenez** [comment]
Hi @PierreOrhan !

> Is it possible to review cutting edge applications of ML current research in a particular field?

Yes but you must tell some story that connects the research to the application.  

> Who are the judges of the contest?

At Mathpix we have a team of ML experts so I take responsibility that we will ensure fair reviews :)  

We also might set up a site where people can vote on their favorite submission - we'll know better once we have the first submissions in.  If some of the content really stands out, we will pick winners manually based on what we think is fair.  If there is too much great content and it's not straightforward to pick the top 3 submissions, we'll use a more crowdsourced approach, as time permits - we of course need to make sure winners get chosen promptly and get their checks!

> Is anyone allowed to compete?

Yes! We will judge by the quality of the exposition and the quality of the ideas only.  A few sentences about your background is encouraged to give more context, but not required.

The goal is to get some great free content up online and get writers paid!
