### ISSUE TITLE
Exact Deadline Time 

### ISSUE THREAD

**Issue by Nickil21** [Mathpix/spectra-review-paper-competition#27]
I wanted to know when is the _exact_ deadline time -- Is it March 15, 2021 (Anywhere on Earth)?

**Comment by nicodjimenez** [comment]
Hi!

> I wanted to know when is the exact deadline time -- Is it March 15, 2021 (Anywhere on Earth)?

March 15th PST (California time).  But anywhere on earth is fine too we will stop accepting submissions March 16th.

**Comment by Nickil21** [comment]
Yup, thanks. I plan to submit before March 15th 23:59:59 (Anywhere on Earth).

**Comment by gabriben** [comment]
same here
