### ISSUE TITLE
Does the competition have started?

### ISSUE THREAD

**Issue by youkaichao** [Mathpix/spectra-review-paper-competition#3]
I'm about to write a review for my paper, only to find that there are few participants. Do I get to the right place for the competition? Only 8 forks and 1 pull requests :)

**Comment by nicodjimenez** [comment]
> I'm about to write a review for my paper, only to find that there are few participants. Do I get to the right place for the competition? Only 8 forks and 1 pull requests :)

Yes this is the right place! Competition is happening no matter what and prizes will go out no matter what.  

We expect many last minute submissions eg #4.  

Looking forward to your submission!
