### ISSUE TITLE
Possible fraud for the winning paper

### ISSUE THREAD

**Issue by PierreOrhan** [Mathpix/spectra-review-paper-competition#49]
The winning paper had support on twitter, more than other papers. But it was subtentially suported by users which account **were created  in march 2021 with between 1 or 2 followers**. @nicodjimenez, @kaitlinmcunningham1 was the competition designed to favor this kind of behavior? How was this taken into account? @mccaffary would you like to answer something about this?

set of profile : 
https://twitter.com/PaulSpe49628373
https://twitter.com/jiali921
https://twitter.com/luppi_dario
https://twitter.com/DamianLyter

As they have no follower, these profile did not help gather more people on the spectra website...
On comparison, the second more backup on twitter was Information Theory in Machine Learning ; its absence on the Podium is troubling and some arbitrary decision seem to have been made. Am I missing something? 

- The second best article was a summary of a previous work presented at NeurIPS . From the exact rules of the contest: 
" - The review paper, however must be original writing and in English
- The goal of the paper should be to summarize/explain cutting edge approaches in a particular subfield of ML (for example machine translation, text summarization, and image segmentation)"
This article reused figures from the original paper, which as far as I can understand the rules above is not an original writing and therefore forbidden. 

The sudden change of deadlines, lacks of transparency in the results statistics and clear non-highlighted frauds in 2 article (see second issue in this thread) makes me a bit worried about the future of the contests, while I still find it a great idea and a great manner for students to train at writing!

**Comment by nicodjimenez** [comment]
Hi @PierreOrhan we did not only look at Twitter votes when considering the winner. 

Choosing winners for review articles written on a wide array of different fields is a near impossible task, as we found out.  

We ended up choosing winners in big part according to what fields of research we felt were most promising and that we should promote to our audience.

Future competitions will be more user moderated than this one.  

Thank you for your support on this!
